// 组件 title
export const nodeTitle = {
  other1: '水波图',
  other2: '旭日图',
  other3: '漏斗图',
  other4: '热力图',
  other5: '子弹图',
  interval1: '区间柱状图',
  interval2: '柱状图',
  interval3: '瀑布图',
  interval4: '玉钰图',
  bar1: '百分比条形图',
  line1: '折线图',
  area1: '区域图',
  pie1: '饼图',
  pie2: '进度环图',
  point1: '基本散点图',
  point2: '气泡图',
  radar1: '雷达图',
  map1: '基础平面地图',
  text1: '词云',
  text2: '跑马灯',
  text3: '通用标题',
  text4: '倒计时',
  text5: '多行文本',
  text6: '时间器',
  table1: '进度条表格',
  table2: '轮播列表',
  widget1: '开关',
  widget2: 'iframe',
  media1: '单张图片',
  media2: '视频',
  media3: '轮播图',
  media4: '装饰线条',
  media5: '箭头描绘',
  media6: '基础图形',
};
