export enum MeterType {
  FCCommand = '0',
  FCRainfall = '1',
  FCWaterLevel = '2',
  FCFlowRate = '3',
  FCFlowSpeed = '4',
  FCGatePosition = '5',
  FCPower = '6',
  FCAirPressure = '7',
  FCWindSpeed = '8',
  FCWaterTemperature = '9',
  FCWaterQuality = '10',
  FCSoilMoisture = '11',
  FCEvaporation = '12',
  FCAlarmStatus = '13',
  FCComprehensive = '14',
  FCWaterPressure = '15',
}

export const meterTypeOptions = {
  [MeterType.FCCommand]: '命令',
  [MeterType.FCRainfall]: '雨量参数',
  [MeterType.FCWaterLevel]: '水位参数',
  [MeterType.FCFlowRate]: '流量(水量)参数',
  [MeterType.FCFlowSpeed]: '流速参数',
  [MeterType.FCGatePosition]: '闸位参数',
  [MeterType.FCPower]: '功率参数',
  [MeterType.FCAirPressure]: '气压参数',
  [MeterType.FCWindSpeed]: '风速参数',
  [MeterType.FCWaterTemperature]: '水温参数',
  [MeterType.FCWaterQuality]: '水质参数',
  [MeterType.FCSoilMoisture]: '土壤含水率参数',
  [MeterType.FCEvaporation]: '蒸发量参数',
  [MeterType.FCAlarmStatus]: '报警或状态参数',
  [MeterType.FCComprehensive]: '综合参数',
  [MeterType.FCWaterPressure]: '水压参数',
};
