name: Release Package
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          sudo apt install zip tree -y
          bash ./release.sh
          tree -d

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.ACCESS_TOKEN }}
          file: _release/www.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: ${{ github.ref }}
